#!/bin/bash
export LANG=C
export LANGUAGE=C
export LC_ALL=C
export http_proxy=http://10.20.30.254:3128/
export https_proxy=http://10.20.30.254:3128/
export ftp_proxy=http://10.20.30.254:3128/
google-chrome-stable --proxy-server=10.20.30.254:3128 --incognito

