#!/bin/bash
JAVA_HOME=/opt/jdk1.6.0_45
JDK_HOME=/opt/jdk1.6.0_45
JAVAC=/opt/jdk1.6.0_45/bin/javac
export JAVA_HOME
export JAVA_JDK
export JAVAC
echo Java home = $JAVA_HOME
echo $JAVA_HOME/bin/javaws $1
$JAVA_HOME/bin/javaws "$1"
